# Generated by Django 2.0.1 on 2021-04-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='邮箱验证码'),
        ),
    ]
